# Find Producer headers and libraries

FIND_PATH( PRODUCER_DIR
		NAMES
			include/Producer/Version
			include/Producer/Version.h
		PATHS
			$ENV{PRODUCER_DIR}
			$ENV{OPENTHREADS_DIR}
			$ENV{OSG_DIR}
			$ENV{OSGDIR}
			${PRODUCER_DIR}
			${OSG_DIR}
			${OPENTHREADS_DIR}
			/usr
			/usr/local
			/sw
			/opt
			/opt/local
			/opt/csw
			/usr/freeware
)

IF( PRODUCER_DIR )
	FIND_PATH( PRODUCER_INCLUDE_DIR
			NAMES
				Producer/Version
				Producer/Version.h
			PATHS
				${PRODUCER_DIR}/include )

	IF( PRODUCER_INCLUDE_DIR )
		FIND_FILE( PRODUCER_VERSION_FILE
				NAMES
					Producer/Version
					Producer/Version.h
				PATHS
					${PRODUCER_INCLUDE_DIR} )

		IF( PRODUCER_VERSION_FILE )
			GET_FILENAME_COMPONENT( PRODUCER_VERSION_FILE_EXTENSION
					${PRODUCER_VERSION_FILE} EXT )
			STRING( TOUPPER "${PRODUCER_VERSION_FILE_EXTENSION}" PRODUCER_VERSION_FILE_EXTENSION )
			IF( ${PRODUCER_VERSION_FILE_EXTENSION} MATCHES "H" )
				SET( PRODUCER_DEFINITION_FLAGS )
			ELSE( ${PRODUCER_VERSION_FILE_EXTENSION} MATCHES "H" )
				SET( PRODUCER_DEFINITION_FLAGS -DOLDPRODUCER )
				ADD_DEFINITIONS( -DOLDPRODUCER )
			ENDIF( ${PRODUCER_VERSION_FILE_EXTENSION} MATCHES "H" )
		ENDIF( PRODUCER_VERSION_FILE )
	ENDIF( PRODUCER_INCLUDE_DIR )

	FIND_LIBRARY( PRODUCER_LIBRARY Producer
			${PRODUCER_DIR}/lib
			${PRODUCER_DIR}/lib64 )

	FIND_LIBRARY( PRODUCER_LIBRARY_DEBUG Producerd
			${PRODUCER_DIR}/lib
			${PRODUCER_DIR}/lib64 )

	IF( PRODUCER_LIBRARY AND NOT PRODUCER_LIBRARY_DEBUG )
		SET( PRODUCER_LIBRARY_DEBUG ${PRODUCER_LIBRARY} CACHE FILEPATH "Debug version of Producer Library (use regular version if not available)" FORCE )
	ENDIF( PRODUCER_LIBRARY AND NOT PRODUCER_LIBRARY_DEBUG )
ENDIF( PRODUCER_DIR )

SET( PRODUCER_FOUND "NO" )
IF( PRODUCER_INCLUDE_DIR AND PRODUCER_LIBRARY )
	SET( PRODUCER_FOUND "YES" )
ENDIF( PRODUCER_INCLUDE_DIR AND PRODUCER_LIBRARY )

